export const USER_LOGIN__STARTED = "USER_LOGIN__STARTED";
export const USER_LOGIN__SUCCESS = "USER_LOGIN__SUCCESS";
export const USER_LOGIN__FAILURE = "USER_LOGIN__FAILURE";
export const USER_REGISTER__STARTED = "USER_REGISTER__STARTED";
export const USER_REGISTER__SUCCESS = "USER_REGISTER__SUCCESS";
export const USER_REGISTER__FAILURE = "USER_REGISTER__FAILURE";
