export const GET_ALL_DIALOG__STARTED = "GET_ALL_DIALOG__STARTED";
export const GET_ALL_DIALOG__SUCCESS = "GET_ALL_DIALOG__SUCCESS";
export const GET_ALL_DIALOG_FAILURE = "GET_ALL_DIALOG_FAILURE";
export const ADD_DIALOG__STARTED = "ADD_DIALOG__STARTED";
export const ADD_DIALOG__SUCCESS = "ADD_DIALOG__SUCCESS";
export const ADD_DIALOG__FAILURE = "ADD_DIALOG__FAILURE";
