export const GET_ALL_MESSAGES__STARTED = "GET_ALL_MESSAGES__STARTED";
export const GET_ALL_MESSAGES__SUCCESS = "GET_ALL_MESSAGES__SUCCESS";
export const GET_ALL_MESSAGES__FAILURE = "GET_ALL_MESSAGES__FAILURE";
