export const GET_USER__STARTED = "GET_USER__STARTED";
export const GET_USER__SUCCESS = "GET_USER__SUCCESS";
export const GET_USER__FAILURE = "GET_USER__FAILURE";

export const PUT_USER__STARTED = "PUT_USER__STARTED";
export const PUT_USER__SUCCESS = "PUT_USER__SUCCESS";
export const PUT_USER__FAILURE = "PUT_USER__FAILURE";

export const DELETE_USER__STARTED = "PUT_USER__STARTED";
export const DELETE_USER__SUCCESS = "PUT_USER__SUCCESS";
export const DELETE_USER__FAILURE = "PUT_USER__FAILURE";
